#!/bin/bash

#PBS -S /bin/bash
#PBS -N test_s_1k
#PBS -l walltime=3:59:00
#PBS -l select=1:ncpus=4:mpiprocs=4
#
# "fusion" PBS options
#PBS -P omaha

# Charge the modules here
# "fusion" cluster modules
# module purge
# module load intel-compilers/17.0.4
# module load intel-mpi/2017.0.3
# module load intel-mkl/2017.0.3
# module load libgmp/6.1.2
# module load libmpfr/3.1.5

# On se place dans le repertoire depuis lequel le job a ete soumis
cd $PBS_O_WORKDIR

mpirun -n 4 ./libmesh_apply_solution_homogeneous -i $CARL_DIR/examples/coupled_traction_test/FETI_solver/brick_traction_1k/apply_solution_brick_traction_A_1k.txt

mpirun -n 4 ./libmesh_apply_solution_homogeneous -i $CARL_DIR/examples/coupled_traction_test/FETI_solver/brick_traction_1k/apply_solution_brick_traction_B_1k.txt  
