#!/bin/bash
#PBS -S /bin/bash
#PBS -N test_i_1ki
#PBS -o ro.txt
#PBS -e re.txt
#PBS -l walltime=3:59:00
#PBS -l select=1:ncpus=4:mpiprocs=4

# "fusion" PBS options
#PBS -P omaha

# Charge the modules here
# "fusion" cluster modules
# module purge
# module load intel-compilers/17.0.4
# module load intel-mpi/2017.0.3
# module load intel-mkl/2017.0.3
# module load libgmp/6.1.2
# module load libmpfr/3.1.5

# On se place dans le repertoire depuis lequel le job a ete soumis
cd $PBS_O_WORKDIR

mkdir -p ./intersection/output/inter_1k

mpirun -np 4 $CARLBUILD/CArl_build_intersections -i ./intersection/inter_traction_test_1k.txt
