#!/bin/sh

module purge
module load git/2.19.0  
module load intel-compilers/2018.2
module load intel-mpi/2018.2
module load intel-mpi/2018.2  
module load libgmp/6.1.2
module load libmpfr/3.1.5
module load cmake/3.14.0 
#module load python/2.7.13

export PETSC_DIR="/home/gattif/srclib/petsc"
export PETSC_ARCH="arch-linux2-cxx-opt"
export CGAL_DIR="/home/gattif/LOCAL/cgal"
export LIBMESH_DIR="/home/gattif/LOCAL/libmesh"
export BOOST_ROOT="home/gattif/LOCAL/boost"
