function ex1()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load ex1                               

a = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'PointerShapeCData',mat1, ...
	'Position',[520 720 560 420]);
b = axes('Parent',a, ...
	'CameraUpVector',[0 0 1], ...
	'Color',[1 1 1], ...
	'ColorOrder',mat2, ...
	'View',[-37.5 30], ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.67357, ...
	'NormalMode','manual', ...
	'VertexNormals',mat3, ...
	'Vertices',mat4);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.53034, ...
	'NormalMode','manual', ...
	'VertexNormals',mat5, ...
	'Vertices',mat6);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.2727, ...
	'NormalMode','manual', ...
	'VertexNormals',mat7, ...
	'Vertices',mat8);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.52544, ...
	'NormalMode','manual', ...
	'VertexNormals',mat9, ...
	'Vertices',mat10);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.04235, ...
	'NormalMode','manual', ...
	'VertexNormals',mat11, ...
	'Vertices',mat12);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.58268, ...
	'NormalMode','manual', ...
	'VertexNormals',mat13, ...
	'Vertices',mat14);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.29511, ...
	'NormalMode','manual', ...
	'VertexNormals',mat15, ...
	'Vertices',mat16);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.71954, ...
	'NormalMode','manual', ...
	'VertexNormals',mat17, ...
	'Vertices',mat18);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.82086, ...
	'NormalMode','manual', ...
	'VertexNormals',mat19, ...
	'Vertices',mat20);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.84567, ...
	'NormalMode','manual', ...
	'VertexNormals',mat21, ...
	'Vertices',mat22);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.17846, ...
	'NormalMode','manual', ...
	'VertexNormals',mat23, ...
	'Vertices',mat24);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.26199, ...
	'NormalMode','manual', ...
	'VertexNormals',mat25, ...
	'Vertices',mat26);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.15205, ...
	'NormalMode','manual', ...
	'VertexNormals',mat27, ...
	'Vertices',mat28);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.97989, ...
	'NormalMode','manual', ...
	'VertexNormals',mat29, ...
	'Vertices',mat30);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.6721, ...
	'NormalMode','manual', ...
	'VertexNormals',mat31, ...
	'Vertices',mat32);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.65248, ...
	'NormalMode','manual', ...
	'VertexNormals',mat33, ...
	'Vertices',mat34);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.53353, ...
	'NormalMode','manual', ...
	'VertexNormals',mat35, ...
	'Vertices',mat36);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.26072, ...
	'NormalMode','manual', ...
	'VertexNormals',mat37, ...
	'Vertices',mat38);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.77991, ...
	'NormalMode','manual', ...
	'VertexNormals',mat39, ...
	'Vertices',mat40);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.8327, ...
	'NormalMode','manual', ...
	'VertexNormals',mat41, ...
	'Vertices',mat42);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.97197, ...
	'NormalMode','manual', ...
	'VertexNormals',mat43, ...
	'Vertices',mat44);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.85274, ...
	'NormalMode','manual', ...
	'VertexNormals',mat45, ...
	'Vertices',mat46);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.57344, ...
	'NormalMode','manual', ...
	'VertexNormals',mat47, ...
	'Vertices',mat48);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.23123, ...
	'NormalMode','manual', ...
	'VertexNormals',mat49, ...
	'Vertices',mat50);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.21116, ...
	'NormalMode','manual', ...
	'VertexNormals',mat51, ...
	'Vertices',mat52);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.61883, ...
	'NormalMode','manual', ...
	'VertexNormals',mat53, ...
	'Vertices',mat54);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.82952, ...
	'NormalMode','manual', ...
	'VertexNormals',mat55, ...
	'Vertices',mat56);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.25597, ...
	'NormalMode','manual', ...
	'VertexNormals',mat57, ...
	'Vertices',mat58);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.00899, ...
	'NormalMode','manual', ...
	'VertexNormals',mat59, ...
	'Vertices',mat60);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.73266, ...
	'NormalMode','manual', ...
	'VertexNormals',mat61, ...
	'Vertices',mat62);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',7.74184, ...
	'NormalMode','manual', ...
	'VertexNormals',mat63, ...
	'Vertices',mat64);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',8.20269, ...
	'NormalMode','manual', ...
	'VertexNormals',mat65, ...
	'Vertices',mat66);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.8649, ...
	'NormalMode','manual', ...
	'VertexNormals',mat67, ...
	'Vertices',mat68);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.50783, ...
	'NormalMode','manual', ...
	'VertexNormals',mat69, ...
	'Vertices',mat70);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.47789, ...
	'NormalMode','manual', ...
	'VertexNormals',mat71, ...
	'Vertices',mat72);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.75199, ...
	'NormalMode','manual', ...
	'VertexNormals',mat73, ...
	'Vertices',mat74);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.20867, ...
	'NormalMode','manual', ...
	'VertexNormals',mat75, ...
	'Vertices',mat76);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.8384, ...
	'NormalMode','manual', ...
	'VertexNormals',mat77, ...
	'Vertices',mat78);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.18421, ...
	'NormalMode','manual', ...
	'VertexNormals',mat79, ...
	'Vertices',mat80);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.17817, ...
	'NormalMode','manual', ...
	'VertexNormals',mat81, ...
	'Vertices',mat82);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.33286, ...
	'NormalMode','manual', ...
	'VertexNormals',mat83, ...
	'Vertices',mat84);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.33364, ...
	'NormalMode','manual', ...
	'VertexNormals',mat85, ...
	'Vertices',mat86);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.16828, ...
	'NormalMode','manual', ...
	'VertexNormals',mat87, ...
	'Vertices',mat88);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.70538, ...
	'NormalMode','manual', ...
	'VertexNormals',mat89, ...
	'Vertices',mat90);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.76572, ...
	'NormalMode','manual', ...
	'VertexNormals',mat91, ...
	'Vertices',mat92);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.69524, ...
	'NormalMode','manual', ...
	'VertexNormals',mat93, ...
	'Vertices',mat94);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',2.77858, ...
	'NormalMode','manual', ...
	'VertexNormals',mat95, ...
	'Vertices',mat96);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',2.33012, ...
	'NormalMode','manual', ...
	'VertexNormals',mat97, ...
	'Vertices',mat98);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',2.95569, ...
	'NormalMode','manual', ...
	'VertexNormals',mat99, ...
	'Vertices',mat100);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.46352, ...
	'NormalMode','manual', ...
	'VertexNormals',mat101, ...
	'Vertices',mat102);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',8.23604, ...
	'NormalMode','manual', ...
	'VertexNormals',mat103, ...
	'Vertices',mat104);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',8.89875, ...
	'NormalMode','manual', ...
	'VertexNormals',mat105, ...
	'Vertices',mat106);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.29968, ...
	'NormalMode','manual', ...
	'VertexNormals',mat107, ...
	'Vertices',mat108);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.50677, ...
	'NormalMode','manual', ...
	'VertexNormals',mat109, ...
	'Vertices',mat110);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',2.57114, ...
	'NormalMode','manual', ...
	'VertexNormals',mat111, ...
	'Vertices',mat112);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',2.56129, ...
	'NormalMode','manual', ...
	'VertexNormals',mat113, ...
	'Vertices',mat114);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',1.87981, ...
	'NormalMode','manual', ...
	'VertexNormals',mat115, ...
	'Vertices',mat116);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',2.60309, ...
	'NormalMode','manual', ...
	'VertexNormals',mat117, ...
	'Vertices',mat118);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',7.0802, ...
	'NormalMode','manual', ...
	'VertexNormals',mat119, ...
	'Vertices',mat120);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.61584, ...
	'NormalMode','manual', ...
	'VertexNormals',mat121, ...
	'Vertices',mat122);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.40094, ...
	'NormalMode','manual', ...
	'VertexNormals',mat123, ...
	'Vertices',mat124);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.79548, ...
	'NormalMode','manual', ...
	'VertexNormals',mat125, ...
	'Vertices',mat126);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.94462, ...
	'NormalMode','manual', ...
	'VertexNormals',mat127, ...
	'Vertices',mat128);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.14432, ...
	'NormalMode','manual', ...
	'VertexNormals',mat129, ...
	'Vertices',mat130);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',7.23493, ...
	'NormalMode','manual', ...
	'VertexNormals',mat131, ...
	'Vertices',mat132);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.64543, ...
	'NormalMode','manual', ...
	'VertexNormals',mat133, ...
	'Vertices',mat134);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.87793, ...
	'NormalMode','manual', ...
	'VertexNormals',mat135, ...
	'Vertices',mat136);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',2.89751, ...
	'NormalMode','manual', ...
	'VertexNormals',mat137, ...
	'Vertices',mat138);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.08368, ...
	'NormalMode','manual', ...
	'VertexNormals',mat139, ...
	'Vertices',mat140);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.53295, ...
	'NormalMode','manual', ...
	'VertexNormals',mat141, ...
	'Vertices',mat142);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.34054, ...
	'NormalMode','manual', ...
	'VertexNormals',mat143, ...
	'Vertices',mat144);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.04912, ...
	'NormalMode','manual', ...
	'VertexNormals',mat145, ...
	'Vertices',mat146);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.31369, ...
	'NormalMode','manual', ...
	'VertexNormals',mat147, ...
	'Vertices',mat148);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.59527, ...
	'NormalMode','manual', ...
	'VertexNormals',mat149, ...
	'Vertices',mat150);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.36268, ...
	'NormalMode','manual', ...
	'VertexNormals',mat151, ...
	'Vertices',mat152);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.57015, ...
	'NormalMode','manual', ...
	'VertexNormals',mat153, ...
	'Vertices',mat154);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.16271, ...
	'NormalMode','manual', ...
	'VertexNormals',mat155, ...
	'Vertices',mat156);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.6195, ...
	'NormalMode','manual', ...
	'VertexNormals',mat157, ...
	'Vertices',mat158);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.07291, ...
	'NormalMode','manual', ...
	'VertexNormals',mat159, ...
	'Vertices',mat160);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.62399, ...
	'NormalMode','manual', ...
	'VertexNormals',mat161, ...
	'Vertices',mat162);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.81596, ...
	'NormalMode','manual', ...
	'VertexNormals',mat163, ...
	'Vertices',mat164);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.72581, ...
	'NormalMode','manual', ...
	'VertexNormals',mat165, ...
	'Vertices',mat166);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.98051, ...
	'NormalMode','manual', ...
	'VertexNormals',mat167, ...
	'Vertices',mat168);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.48511, ...
	'NormalMode','manual', ...
	'VertexNormals',mat169, ...
	'Vertices',mat170);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.50755, ...
	'NormalMode','manual', ...
	'VertexNormals',mat171, ...
	'Vertices',mat172);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.40183, ...
	'NormalMode','manual', ...
	'VertexNormals',mat173, ...
	'Vertices',mat174);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.77303, ...
	'NormalMode','manual', ...
	'VertexNormals',mat175, ...
	'Vertices',mat176);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.57267, ...
	'NormalMode','manual', ...
	'VertexNormals',mat177, ...
	'Vertices',mat178);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.27581, ...
	'NormalMode','manual', ...
	'VertexNormals',mat179, ...
	'Vertices',mat180);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.41057, ...
	'NormalMode','manual', ...
	'VertexNormals',mat181, ...
	'Vertices',mat182);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.99406, ...
	'NormalMode','manual', ...
	'VertexNormals',mat183, ...
	'Vertices',mat184);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.14714, ...
	'NormalMode','manual', ...
	'VertexNormals',mat185, ...
	'Vertices',mat186);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',7.55485, ...
	'NormalMode','manual', ...
	'VertexNormals',mat187, ...
	'Vertices',mat188);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.48307, ...
	'NormalMode','manual', ...
	'VertexNormals',mat189, ...
	'Vertices',mat190);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.30543, ...
	'NormalMode','manual', ...
	'VertexNormals',mat191, ...
	'Vertices',mat192);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.47655, ...
	'NormalMode','manual', ...
	'VertexNormals',mat193, ...
	'Vertices',mat194);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.4603, ...
	'NormalMode','manual', ...
	'VertexNormals',mat195, ...
	'Vertices',mat196);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.96452, ...
	'NormalMode','manual', ...
	'VertexNormals',mat197, ...
	'Vertices',mat198);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.25052, ...
	'NormalMode','manual', ...
	'VertexNormals',mat199, ...
	'Vertices',mat200);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',2.15338, ...
	'NormalMode','manual', ...
	'VertexNormals',mat201, ...
	'Vertices',mat202);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',8.17654, ...
	'NormalMode','manual', ...
	'VertexNormals',mat203, ...
	'Vertices',mat204);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',7.86261, ...
	'NormalMode','manual', ...
	'VertexNormals',mat205, ...
	'Vertices',mat206);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.52479, ...
	'NormalMode','manual', ...
	'VertexNormals',mat207, ...
	'Vertices',mat208);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.22575, ...
	'NormalMode','manual', ...
	'VertexNormals',mat209, ...
	'Vertices',mat210);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.89074, ...
	'NormalMode','manual', ...
	'VertexNormals',mat211, ...
	'Vertices',mat212);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.48544, ...
	'NormalMode','manual', ...
	'VertexNormals',mat213, ...
	'Vertices',mat214);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.52998, ...
	'NormalMode','manual', ...
	'VertexNormals',mat215, ...
	'Vertices',mat216);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.92029, ...
	'NormalMode','manual', ...
	'VertexNormals',mat217, ...
	'Vertices',mat218);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.03055, ...
	'NormalMode','manual', ...
	'VertexNormals',mat219, ...
	'Vertices',mat220);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.11807, ...
	'NormalMode','manual', ...
	'VertexNormals',mat221, ...
	'Vertices',mat222);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.04222, ...
	'NormalMode','manual', ...
	'VertexNormals',mat223, ...
	'Vertices',mat224);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.10784, ...
	'NormalMode','manual', ...
	'VertexNormals',mat225, ...
	'Vertices',mat226);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',8.58647, ...
	'NormalMode','manual', ...
	'VertexNormals',mat227, ...
	'Vertices',mat228);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',7.99676, ...
	'NormalMode','manual', ...
	'VertexNormals',mat229, ...
	'Vertices',mat230);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.81989, ...
	'NormalMode','manual', ...
	'VertexNormals',mat231, ...
	'Vertices',mat232);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.95808, ...
	'NormalMode','manual', ...
	'VertexNormals',mat233, ...
	'Vertices',mat234);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.07052, ...
	'NormalMode','manual', ...
	'VertexNormals',mat235, ...
	'Vertices',mat236);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.99801, ...
	'NormalMode','manual', ...
	'VertexNormals',mat237, ...
	'Vertices',mat238);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',9.45417, ...
	'NormalMode','manual', ...
	'VertexNormals',mat239, ...
	'Vertices',mat240);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',8.63476, ...
	'NormalMode','manual', ...
	'VertexNormals',mat241, ...
	'Vertices',mat242);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',9.32465, ...
	'NormalMode','manual', ...
	'VertexNormals',mat243, ...
	'Vertices',mat244);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',9.52642, ...
	'NormalMode','manual', ...
	'VertexNormals',mat245, ...
	'Vertices',mat246);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',1.62572, ...
	'NormalMode','manual', ...
	'VertexNormals',mat247, ...
	'Vertices',mat248);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',2.93227, ...
	'NormalMode','manual', ...
	'VertexNormals',mat249, ...
	'Vertices',mat250);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',8.81495, ...
	'NormalMode','manual', ...
	'VertexNormals',mat251, ...
	'Vertices',mat252);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',7.973, ...
	'NormalMode','manual', ...
	'VertexNormals',mat253, ...
	'Vertices',mat254);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',7.22713, ...
	'NormalMode','manual', ...
	'VertexNormals',mat255, ...
	'Vertices',mat256);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.77581, ...
	'NormalMode','manual', ...
	'VertexNormals',mat257, ...
	'Vertices',mat258);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.25553, ...
	'NormalMode','manual', ...
	'VertexNormals',mat259, ...
	'Vertices',mat260);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',2.05763, ...
	'NormalMode','manual', ...
	'VertexNormals',mat261, ...
	'Vertices',mat262);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',1.67453, ...
	'NormalMode','manual', ...
	'VertexNormals',mat263, ...
	'Vertices',mat264);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',1.83036, ...
	'NormalMode','manual', ...
	'VertexNormals',mat265, ...
	'Vertices',mat266);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',7.4162, ...
	'NormalMode','manual', ...
	'VertexNormals',mat267, ...
	'Vertices',mat268);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',8.58096, ...
	'NormalMode','manual', ...
	'VertexNormals',mat269, ...
	'Vertices',mat270);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',0.46634, ...
	'NormalMode','manual', ...
	'VertexNormals',mat271, ...
	'Vertices',mat272);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',0.981154, ...
	'NormalMode','manual', ...
	'VertexNormals',mat273, ...
	'Vertices',mat274);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.1532, ...
	'NormalMode','manual', ...
	'VertexNormals',mat275, ...
	'Vertices',mat276);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',7.49646, ...
	'NormalMode','manual', ...
	'VertexNormals',mat277, ...
	'Vertices',mat278);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',0.423796, ...
	'NormalMode','manual', ...
	'VertexNormals',mat279, ...
	'Vertices',mat280);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',1.13013, ...
	'NormalMode','manual', ...
	'VertexNormals',mat281, ...
	'Vertices',mat282);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',2.96377, ...
	'NormalMode','manual', ...
	'VertexNormals',mat283, ...
	'Vertices',mat284);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',2.29638, ...
	'NormalMode','manual', ...
	'VertexNormals',mat285, ...
	'Vertices',mat286);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',8.60391, ...
	'NormalMode','manual', ...
	'VertexNormals',mat287, ...
	'Vertices',mat288);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.66433, ...
	'NormalMode','manual', ...
	'VertexNormals',mat289, ...
	'Vertices',mat290);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.89581, ...
	'NormalMode','manual', ...
	'VertexNormals',mat291, ...
	'Vertices',mat292);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.48213, ...
	'NormalMode','manual', ...
	'VertexNormals',mat293, ...
	'Vertices',mat294);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.3858, ...
	'NormalMode','manual', ...
	'VertexNormals',mat295, ...
	'Vertices',mat296);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.41083, ...
	'NormalMode','manual', ...
	'VertexNormals',mat297, ...
	'Vertices',mat298);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.32515, ...
	'NormalMode','manual', ...
	'VertexNormals',mat299, ...
	'Vertices',mat300);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.58727, ...
	'NormalMode','manual', ...
	'VertexNormals',mat301, ...
	'Vertices',mat302);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',7.39979, ...
	'NormalMode','manual', ...
	'VertexNormals',mat303, ...
	'Vertices',mat304);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.14969, ...
	'NormalMode','manual', ...
	'VertexNormals',mat305, ...
	'Vertices',mat306);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',7.0459, ...
	'NormalMode','manual', ...
	'VertexNormals',mat307, ...
	'Vertices',mat308);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.40022, ...
	'NormalMode','manual', ...
	'VertexNormals',mat309, ...
	'Vertices',mat310);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',2.18251, ...
	'NormalMode','manual', ...
	'VertexNormals',mat311, ...
	'Vertices',mat312);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.21299, ...
	'NormalMode','manual', ...
	'VertexNormals',mat313, ...
	'Vertices',mat314);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.96183, ...
	'NormalMode','manual', ...
	'VertexNormals',mat315, ...
	'Vertices',mat316);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.43125, ...
	'NormalMode','manual', ...
	'VertexNormals',mat317, ...
	'Vertices',mat318);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.31836, ...
	'NormalMode','manual', ...
	'VertexNormals',mat319, ...
	'Vertices',mat320);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.72464, ...
	'NormalMode','manual', ...
	'VertexNormals',mat321, ...
	'Vertices',mat322);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.36482, ...
	'NormalMode','manual', ...
	'VertexNormals',mat323, ...
	'Vertices',mat324);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.14562, ...
	'NormalMode','manual', ...
	'VertexNormals',mat325, ...
	'Vertices',mat326);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.0728, ...
	'NormalMode','manual', ...
	'VertexNormals',mat327, ...
	'Vertices',mat328);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.9288, ...
	'NormalMode','manual', ...
	'VertexNormals',mat329, ...
	'Vertices',mat330);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.05734, ...
	'NormalMode','manual', ...
	'VertexNormals',mat331, ...
	'Vertices',mat332);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.76094, ...
	'NormalMode','manual', ...
	'VertexNormals',mat333, ...
	'Vertices',mat334);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.51582, ...
	'NormalMode','manual', ...
	'VertexNormals',mat335, ...
	'Vertices',mat336);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',8.20274, ...
	'NormalMode','manual', ...
	'VertexNormals',mat337, ...
	'Vertices',mat338);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',0.997737, ...
	'NormalMode','manual', ...
	'VertexNormals',mat339, ...
	'Vertices',mat340);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',1.5572, ...
	'NormalMode','manual', ...
	'VertexNormals',mat341, ...
	'Vertices',mat342);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',9.15184, ...
	'NormalMode','manual', ...
	'VertexNormals',mat343, ...
	'Vertices',mat344);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',9.18407, ...
	'NormalMode','manual', ...
	'VertexNormals',mat345, ...
	'Vertices',mat346);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',1.29224, ...
	'NormalMode','manual', ...
	'VertexNormals',mat347, ...
	'Vertices',mat348);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',0.949149, ...
	'NormalMode','manual', ...
	'VertexNormals',mat349, ...
	'Vertices',mat350);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',8.94043, ...
	'NormalMode','manual', ...
	'VertexNormals',mat351, ...
	'Vertices',mat352);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',8.08192, ...
	'NormalMode','manual', ...
	'VertexNormals',mat353, ...
	'Vertices',mat354);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',8.78279, ...
	'NormalMode','manual', ...
	'VertexNormals',mat355, ...
	'Vertices',mat356);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',9.667, ...
	'NormalMode','manual', ...
	'VertexNormals',mat357, ...
	'Vertices',mat358);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',0.84652, ...
	'NormalMode','manual', ...
	'VertexNormals',mat359, ...
	'Vertices',mat360);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',1.43487, ...
	'NormalMode','manual', ...
	'VertexNormals',mat361, ...
	'Vertices',mat362);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',2.25552, ...
	'NormalMode','manual', ...
	'VertexNormals',mat363, ...
	'Vertices',mat364);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',1.20966, ...
	'NormalMode','manual', ...
	'VertexNormals',mat365, ...
	'Vertices',mat366);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',8.17867, ...
	'NormalMode','manual', ...
	'VertexNormals',mat367, ...
	'Vertices',mat368);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',9.45658, ...
	'NormalMode','manual', ...
	'VertexNormals',mat369, ...
	'Vertices',mat370);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',1.521, ...
	'NormalMode','manual', ...
	'VertexNormals',mat371, ...
	'Vertices',mat372);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',2.97192, ...
	'NormalMode','manual', ...
	'VertexNormals',mat373, ...
	'Vertices',mat374);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',7.05157, ...
	'NormalMode','manual', ...
	'VertexNormals',mat375, ...
	'Vertices',mat376);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',7.60753, ...
	'NormalMode','manual', ...
	'VertexNormals',mat377, ...
	'Vertices',mat378);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',9.22811, ...
	'NormalMode','manual', ...
	'VertexNormals',mat379, ...
	'Vertices',mat380);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.93726, ...
	'NormalMode','manual', ...
	'VertexNormals',mat381, ...
	'Vertices',mat382);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',0.369742, ...
	'NormalMode','manual', ...
	'VertexNormals',mat383, ...
	'Vertices',mat384);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',1.77485, ...
	'NormalMode','manual', ...
	'VertexNormals',mat385, ...
	'Vertices',mat386);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.83743, ...
	'NormalMode','manual', ...
	'VertexNormals',mat387, ...
	'Vertices',mat388);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.96155, ...
	'NormalMode','manual', ...
	'VertexNormals',mat389, ...
	'Vertices',mat390);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',8.69333, ...
	'NormalMode','manual', ...
	'VertexNormals',mat391, ...
	'Vertices',mat392);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.78859, ...
	'NormalMode','manual', ...
	'VertexNormals',mat393, ...
	'Vertices',mat394);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',1.23784, ...
	'NormalMode','manual', ...
	'VertexNormals',mat395, ...
	'Vertices',mat396);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',2.69815, ...
	'NormalMode','manual', ...
	'VertexNormals',mat397, ...
	'Vertices',mat398);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.03566, ...
	'NormalMode','manual', ...
	'VertexNormals',mat399, ...
	'Vertices',mat400);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.01277, ...
	'NormalMode','manual', ...
	'VertexNormals',mat401, ...
	'Vertices',mat402);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.71608, ...
	'NormalMode','manual', ...
	'VertexNormals',mat403, ...
	'Vertices',mat404);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.4498, ...
	'NormalMode','manual', ...
	'VertexNormals',mat405, ...
	'Vertices',mat406);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.46694, ...
	'NormalMode','manual', ...
	'VertexNormals',mat407, ...
	'Vertices',mat408);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.55498, ...
	'NormalMode','manual', ...
	'VertexNormals',mat409, ...
	'Vertices',mat410);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.76241, ...
	'NormalMode','manual', ...
	'VertexNormals',mat411, ...
	'Vertices',mat412);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',2.9373, ...
	'NormalMode','manual', ...
	'VertexNormals',mat413, ...
	'Vertices',mat414);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',2.5063, ...
	'NormalMode','manual', ...
	'VertexNormals',mat415, ...
	'Vertices',mat416);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',2.2507, ...
	'NormalMode','manual', ...
	'VertexNormals',mat417, ...
	'Vertices',mat418);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',7.98324, ...
	'NormalMode','manual', ...
	'VertexNormals',mat419, ...
	'Vertices',mat420);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',7.48706, ...
	'NormalMode','manual', ...
	'VertexNormals',mat421, ...
	'Vertices',mat422);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.19315, ...
	'NormalMode','manual', ...
	'VertexNormals',mat423, ...
	'Vertices',mat424);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.12246, ...
	'NormalMode','manual', ...
	'VertexNormals',mat425, ...
	'Vertices',mat426);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.36487, ...
	'NormalMode','manual', ...
	'VertexNormals',mat427, ...
	'Vertices',mat428);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',7.39442, ...
	'NormalMode','manual', ...
	'VertexNormals',mat429, ...
	'Vertices',mat430);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',1.87269, ...
	'NormalMode','manual', ...
	'VertexNormals',mat431, ...
	'Vertices',mat432);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.88668, ...
	'NormalMode','manual', ...
	'VertexNormals',mat433, ...
	'Vertices',mat434);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',7.65595, ...
	'NormalMode','manual', ...
	'VertexNormals',mat435, ...
	'Vertices',mat436);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',8.84967, ...
	'NormalMode','manual', ...
	'VertexNormals',mat437, ...
	'Vertices',mat438);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',7.54742, ...
	'NormalMode','manual', ...
	'VertexNormals',mat439, ...
	'Vertices',mat440);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.95611, ...
	'NormalMode','manual', ...
	'VertexNormals',mat441, ...
	'Vertices',mat442);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.07908, ...
	'NormalMode','manual', ...
	'VertexNormals',mat443, ...
	'Vertices',mat444);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.2488, ...
	'NormalMode','manual', ...
	'VertexNormals',mat445, ...
	'Vertices',mat446);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',0.224599, ...
	'NormalMode','manual', ...
	'VertexNormals',mat447, ...
	'Vertices',mat448);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.80004, ...
	'NormalMode','manual', ...
	'VertexNormals',mat449, ...
	'Vertices',mat450);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.75433, ...
	'NormalMode','manual', ...
	'VertexNormals',mat451, ...
	'Vertices',mat452);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.08834, ...
	'NormalMode','manual', ...
	'VertexNormals',mat453, ...
	'Vertices',mat454);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',9.33754, ...
	'NormalMode','manual', ...
	'VertexNormals',mat455, ...
	'Vertices',mat456);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',9.84335, ...
	'NormalMode','manual', ...
	'VertexNormals',mat457, ...
	'Vertices',mat458);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',0.745558, ...
	'NormalMode','manual', ...
	'VertexNormals',mat459, ...
	'Vertices',mat460);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',1.05823, ...
	'NormalMode','manual', ...
	'VertexNormals',mat461, ...
	'Vertices',mat462);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.92552, ...
	'NormalMode','manual', ...
	'VertexNormals',mat463, ...
	'Vertices',mat464);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',1.83751, ...
	'NormalMode','manual', ...
	'VertexNormals',mat465, ...
	'Vertices',mat466);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',8.69178, ...
	'NormalMode','manual', ...
	'VertexNormals',mat467, ...
	'Vertices',mat468);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',9.29869, ...
	'NormalMode','manual', ...
	'VertexNormals',mat469, ...
	'Vertices',mat470);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.08602, ...
	'NormalMode','manual', ...
	'VertexNormals',mat471, ...
	'Vertices',mat472);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',2.31917, ...
	'NormalMode','manual', ...
	'VertexNormals',mat473, ...
	'Vertices',mat474);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',7.55685, ...
	'NormalMode','manual', ...
	'VertexNormals',mat475, ...
	'Vertices',mat476);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',9.42128, ...
	'NormalMode','manual', ...
	'VertexNormals',mat477, ...
	'Vertices',mat478);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.26793, ...
	'NormalMode','manual', ...
	'VertexNormals',mat479, ...
	'Vertices',mat480);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.92264, ...
	'NormalMode','manual', ...
	'VertexNormals',mat481, ...
	'Vertices',mat482);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',8.10794, ...
	'NormalMode','manual', ...
	'VertexNormals',mat483, ...
	'Vertices',mat484);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',9.6756, ...
	'NormalMode','manual', ...
	'VertexNormals',mat485, ...
	'Vertices',mat486);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',9.83224, ...
	'NormalMode','manual', ...
	'VertexNormals',mat487, ...
	'Vertices',mat488);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',9.83475, ...
	'NormalMode','manual', ...
	'VertexNormals',mat489, ...
	'Vertices',mat490);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',9.72961, ...
	'NormalMode','manual', ...
	'VertexNormals',mat491, ...
	'Vertices',mat492);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',0.199197, ...
	'NormalMode','manual', ...
	'VertexNormals',mat493, ...
	'Vertices',mat494);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.90093, ...
	'NormalMode','manual', ...
	'VertexNormals',mat495, ...
	'Vertices',mat496);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',0.5054, ...
	'NormalMode','manual', ...
	'VertexNormals',mat497, ...
	'Vertices',mat498);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',0.251099, ...
	'NormalMode','manual', ...
	'VertexNormals',mat499, ...
	'Vertices',mat500);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.94089, ...
	'NormalMode','manual', ...
	'VertexNormals',mat501, ...
	'Vertices',mat502);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.64588, ...
	'NormalMode','manual', ...
	'VertexNormals',mat503, ...
	'Vertices',mat504);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',9.72456, ...
	'NormalMode','manual', ...
	'VertexNormals',mat505, ...
	'Vertices',mat506);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',0.254301, ...
	'NormalMode','manual', ...
	'VertexNormals',mat507, ...
	'Vertices',mat508);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.03633, ...
	'NormalMode','manual', ...
	'VertexNormals',mat509, ...
	'Vertices',mat510);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.35587, ...
	'NormalMode','manual', ...
	'VertexNormals',mat511, ...
	'Vertices',mat512);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',0.685003, ...
	'NormalMode','manual', ...
	'VertexNormals',mat513, ...
	'Vertices',mat514);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',0.82386, ...
	'NormalMode','manual', ...
	'VertexNormals',mat515, ...
	'Vertices',mat516);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',1.19836, ...
	'NormalMode','manual', ...
	'VertexNormals',mat517, ...
	'Vertices',mat518);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',0.448044, ...
	'NormalMode','manual', ...
	'VertexNormals',mat519, ...
	'Vertices',mat520);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',1.97626, ...
	'NormalMode','manual', ...
	'VertexNormals',mat521, ...
	'Vertices',mat522);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',0.170546, ...
	'NormalMode','manual', ...
	'VertexNormals',mat523, ...
	'Vertices',mat524);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',0.496042, ...
	'NormalMode','manual', ...
	'VertexNormals',mat525, ...
	'Vertices',mat526);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',2.70343, ...
	'NormalMode','manual', ...
	'VertexNormals',mat527, ...
	'Vertices',mat528);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.29631, ...
	'NormalMode','manual', ...
	'VertexNormals',mat529, ...
	'Vertices',mat530);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',0.241741, ...
	'NormalMode','manual', ...
	'VertexNormals',mat531, ...
	'Vertices',mat532);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',3.9497, ...
	'NormalMode','manual', ...
	'VertexNormals',mat533, ...
	'Vertices',mat534);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.33678, ...
	'NormalMode','manual', ...
	'VertexNormals',mat535, ...
	'Vertices',mat536);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.89005, ...
	'NormalMode','manual', ...
	'VertexNormals',mat537, ...
	'Vertices',mat538);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.01633, ...
	'NormalMode','manual', ...
	'VertexNormals',mat539, ...
	'Vertices',mat540);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.109, ...
	'NormalMode','manual', ...
	'VertexNormals',mat541, ...
	'Vertices',mat542);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',4.98321, ...
	'NormalMode','manual', ...
	'VertexNormals',mat543, ...
	'Vertices',mat544);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.65058, ...
	'NormalMode','manual', ...
	'VertexNormals',mat545, ...
	'Vertices',mat546);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.12934, ...
	'NormalMode','manual', ...
	'VertexNormals',mat547, ...
	'Vertices',mat548);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',6.66051, ...
	'NormalMode','manual', ...
	'VertexNormals',mat549, ...
	'Vertices',mat550);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',7.26824, ...
	'NormalMode','manual', ...
	'VertexNormals',mat551, ...
	'Vertices',mat552);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',7.92066, ...
	'NormalMode','manual', ...
	'VertexNormals',mat553, ...
	'Vertices',mat554);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',8.84058, ...
	'NormalMode','manual', ...
	'VertexNormals',mat555, ...
	'Vertices',mat556);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',5.52649, ...
	'NormalMode','manual', ...
	'VertexNormals',mat557, ...
	'Vertices',mat558);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',9.56617, ...
	'NormalMode','manual', ...
	'VertexNormals',mat559, ...
	'Vertices',mat560);
c = patch('Parent',b, ...
	'FaceColor','flat', ...
	'FaceVertexCData',9.73202, ...
	'NormalMode','manual', ...
	'VertexNormals',mat561, ...
	'Vertices',mat562);
